###########################################
# geo2fastq configuration file
# adapt these settings for your environment
###########################################

# genome files ---------------------------

#Path where you keep genome files
genome_dir: /data/genomes 

# Define, what genome assembly you want to use for what organism. Give 
# it as taxonimc_id: genomeAssembly. Genome assembly names must match 
# with the folder names in you genome_dir location.
genome_build:
        8364:   xenTro3beta
        7955:   danRer7
        9606:   hg19
        10090:  mm10
        10116:  rn4
        8355:   XENLA_JGIv7b


# data conversion -----------------------

# Alignment program to use for mapping.
aligner:
        default: bwa
        RNA-Seq: gsnap
        ChIP-Seq: bwa

# Command structure for the alignment wrapper. 
ALIGN_CMD: /opt/soladmin/current/script/soladmin_align.rb -i {0} -o {1} -g {2} -a {3} -r {4}


# trackhub uploads --------------------

#local path to the directory where the trackhubs are to be published
HUB_LOCALBASE: /mnt/trackhub/tmp/

#internet path under which the trackhub directory will be accessible from outside
HUB_URLBASE: http://trackhub.science.ru.nl/tmp/

#email address of responsible person
email: user@example.com

