genome_dir: /data/genomes

aligner:
        default: bwa
        RNA-Seq: gsnap
        ChIP-Seq: bwa

genome_build:
        8364:   xenTro3beta
        7955:   danRer7
        9606:   hg19
        10090:  mm10
        10116:  rn4
        8355:   XENLA_JGIv7b
